workflows:
  mongo-assistant-workflow:
    name: Mongo Assistant Pipeline
    scripts:
      - name: Run Hello Pipeline for Mongo Assistant
        script: echo "Creating Build"

    publishing:
      email:
        recipients:
          - aneeshprabu@gmail.com

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
      cancel_previous_builds: true

    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: master
      cancel_previous_builds: true

        
    
