workflows:
  mongo-assistant-workflow:
    name: Mongo Assistant Pipeline
    scripts:
      - name: Run Hello Pipeline for Mongo Assistant
        script: echo "Welcome to Mongo Assistant. Please wait while we test your build!"

      - name: Run Mongo Assistant Tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --workspace ${XCODE_WORKSPACE?} \
              --scheme ${XCODE_SCHEME?} \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml

    publishing:
      email:
        recipients:
          - aneeshprabu@gmail.com

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
      cancel_previous_builds: true

    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: master
      cancel_previous_builds: true

        
    
