workflows:
  mongo-assistant-workflow:
    name: Mongo Assistant Pipeline
    scripts:
      - name: say hello
        script: echo "Welcome to Mongo Assistant. Please wait while we test your build!"
  test-workflow:
    scripts:
      - name: Run mongo assistant tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --workspace ${XCODE_WORKSPACE?} \
              --scheme ${XCODE_SCHEME?} \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml
  email-publishing-workflow:
    publishing:
      email:
        recipients:
          - aneesh.prabu@gmail.com
  push-to-master-workflow:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: false
      cancel_previous_builds: true
  pr-workflow:
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: master
      cancel_previous_builds: true

  build-using-cordova-workflow:
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command
          
          cvm install 9.0.0
          cvm use 9.0.0
      - name: Add iOS platform
        script: |
          set -e # exit on first failed command

          cordova platform remove ios --nosave
          cordova platform add ios --confirm --no-interactive --noresources --save
      - name: Build iOS release
        script: |
          set -e # exit on first failed command

          cordova build ios --no-interactive

        
    
