workflows:
  mongo-assistant-workflow:
    name: Mongo Assistant Pipeline
    scripts:
      - name: Run Build Pipeline for Mongo Assistant
        script: echo "Creating Build"

    publishing:
      email:
        recipients:
          - aneeshprabu@gmail.com

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
      cancel_previous_builds: true
      
  tests-workflow:
    scripts:
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --workspace MongoGPT3Demo.xcworkspace \
              --scheme MongoGPT3Demo \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml

